version: "3.9"
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/
    ports:
      - 80:80

  maria_db:
    container_name: bekas-mariadb
    image: mariadb:11.2
    restart: always
    environment:
      MYSQL_DATABASE: hotelmanagement
      MYSQL_USER: mangsacoding
      MYSQL_PASSWORD: developer
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d/database.sql.gz

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: bekas-myadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=maria_db
      - PMA_PORT=3306
      - PMA_USER=mangsacoding
      - PMA_PASSWORD=developer
    depends_on:
      - maria_db

  cron-backup:
    container_name: backup-sql
    image: fradelg/mysql-cron-backup
    depends_on:
      - maria_db
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=maria_db
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MAX_BACKUPS=15
      - INIT_RESTORE_LATEST=1
      - EXIT_BACKUP=1
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
      # Make it small
      - GZIP_LEVEL=9
    restart: unless-stopped

volumes:
  data:
